<?xml version="1.0"?>
<robot name="ackermann_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <!-- Propiedades -->
  <xacro:property name="wheel_radius" value="0.15"/>
  <xacro:property name="wheel_width" value="0.05"/>
  <xacro:property name="wheel_separation" value="1.0"/>
  <xacro:property name="wheelbase" value="1.5"/>
  <xacro:property name="chassis_mass" value="20.0"/>
  <xacro:property name="wheel_mass" value="1.0"/>
  <xacro:property name="PI" value="3.14159265359"/>
  <!-- Chasis -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${wheelbase} ${wheel_separation} 0.1"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <box size="${wheelbase} ${wheel_separation} 0.1"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${chassis_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.5" ixy="0.0" ixz="0.0" iyy="0.5" iyz="0.0" izz="0.5"/>
    </inertial>
  </link>

  <!-- Ruedas Traseras -->
  <link name="left_rear_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>
  <link name="right_rear_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Ruedas Delanteras -->
  <link name="left_front_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>
  <link name="right_front_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Juntas de las Ruedas -->
  <joint name="left_rear_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_rear_wheel"/>
    <origin xyz="-${wheelbase / 2} ${wheel_separation / 2} 0" rpy="${PI/2} 0 0"/>   
    <axis xyz="0 0 1"/>
  </joint>
  <joint name="right_rear_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_rear_wheel"/>
    <origin xyz="-${wheelbase / 2} -${wheel_separation / 2} 0 " rpy="${PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>
  <joint name="left_front_wheel_joint" type="revolute">
    <parent link="base_link"/>
    <child link="left_front_wheel"/>
    <origin xyz="${wheelbase / 2} ${wheel_separation / 2} 0" rpy="${PI/2} 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="50.0" velocity="1.0" lower="-0.785" upper="0.785"/>
  </joint>

  <joint name="right_front_wheel_joint" type="revolute">
    <parent link="base_link"/>
    <child link="right_front_wheel"/>
    <origin xyz="${wheelbase / 2} -${wheel_separation / 2} 0" rpy="${PI/2} 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="50.0" velocity="1.0" lower="-0.785" upper="0.785"/>
  </joint>

</robot>
