controller_manager:
  ros__parameters:
    update_rate: 50  # Frecuencia de actualización del controlador (Hz)
    use_sim_time: false  # Si estás usando tiempo simulado
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController
    # ackermann_hardware:  # Asegúrate de que este nombre coincida con el del bloque de parámetros
    #   type: ackermann_robot/AckermannHardwareInterface

ackermann_steering_controller:
  ros__parameters:
    reference_timeout: 2.0
    front_steering: true
    open_loop: true
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: true
    enable_odom_tf: true
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    rear_wheels_names: ["motor_joint"]
    front_wheels_names: ["steering_joint"]
    wheelbase: 1.0
    front_wheel_track: 0.55
    rear_wheel_track: 0.55
    front_wheels_radius: 0.1
    rear_wheels_radius: 0.1

ackermann_hardware:  # Este nombre debe coincidir con el declarado en el bloque de controller_manager
  ros__parameters:
    motor_name: "motor_joint"
    steering_name: "steering_joint"
    debug: false
    max_ang_motor: 100 
    min_ang_motor: 86
    max_ang_steering: 115
    min_ang_steering: 65
